#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR=$(cd "$(dirname "$0")" && pwd)
ENV_FILE="$ROOT_DIR/.env"
VENV_DIR="$ROOT_DIR/.venv"
TLS_DIR="$ROOT_DIR/configs/tls"
AUTO_TLS_CERT="$TLS_DIR/webadmin.crt"
AUTO_TLS_KEY="$TLS_DIR/webadmin.key"
PID_FILE="$ROOT_DIR/.gntl-webadmin.pid"
APP_ENTRY="gntl.main"
BACKEND_SRC_DIR="$ROOT_DIR/backend/src"
MOBILE_DOCROOT="$ROOT_DIR/mobile"
MOBILE_ROUTER="$MOBILE_DOCROOT/router.php"
MOBILE_PHP_PORT="${GNTL_MOBILE_PHP_PORT:-2027}"
MOBILE_LOG_DIR="$ROOT_DIR/configs/logs"
MOBILE_USE_CADDY="${GNTL_MOBILE_USE_CADDY:-1}"
FRPC_BIN="$ROOT_DIR/bin/frpc"
FRPC_STATE_FILE="$ROOT_DIR/configs/instances_state.json"
FRPC_PID_DIR="$ROOT_DIR/configs"
PHP_BIN="${GNTL_PHP_BIN:-}"
FRONTEND_DIR="$ROOT_DIR/frontend"
FRONTEND_BUILD_STAMP="$ROOT_DIR/configs/.frontend_build.sha256"
FRONTEND_DEV_PORT="${GNTL_FRONTEND_PORT:-5173}"
BIND_HOST="${GNTL_BIND_HOST:-0.0.0.0}"
FRONTEND_DEV_HOST="${GNTL_FRONTEND_HOST:-0.0.0.0}"
AUTO_OPEN_APP="${GNTL_AUTO_OPEN_APP:-1}"
NODE_MIN_MAJOR="${GNTL_NODE_MIN_MAJOR:-18}"
NODE_INSTALL_MAJOR="${GNTL_NODE_INSTALL_MAJOR:-20}"
NODE_LOCAL_INSTALL="${GNTL_NODE_LOCAL_INSTALL:-0}"
LOCAL_NODE_DIR="$ROOT_DIR/bin/node"
ENABLE_TUNNELS="${GNTL_ENABLE_TUNNELS:-1}"
UBUNTU_BOOTSTRAP="${GNTL_UBUNTU_BOOTSTRAP:-0}"
TUNNEL_TAG="mobile"

cd "$ROOT_DIR"

# Helper: print to stderr
err() { printf "%s\n" "$*" >&2; }

ensure_and_load_env_defaults() {
  local mobile_caddy_key_pattern mobile_auth_key_pattern
  mobile_caddy_key_pattern='^[[:space:]]*GNTL_MOBILE_USE_CADDY='
  mobile_auth_key_pattern='^[[:space:]]*GNTL_MOBILE_REQUIRE_AUTH='

  if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" <<'EOF'
# Auto-generated by run.sh
GNTL_MOBILE_USE_CADDY=1
GNTL_MOBILE_REQUIRE_AUTH=1
EOF
    err "[config] Created .env with default mobile settings"
  else
    if ! grep -Eq "$mobile_caddy_key_pattern" "$ENV_FILE" 2>/dev/null; then
      printf '\nGNTL_MOBILE_USE_CADDY=1\n' >> "$ENV_FILE"
      err "[config] Added GNTL_MOBILE_USE_CADDY=1 to .env"
    fi
    if ! grep -Eq "$mobile_auth_key_pattern" "$ENV_FILE" 2>/dev/null; then
      printf '\nGNTL_MOBILE_REQUIRE_AUTH=1\n' >> "$ENV_FILE"
      err "[config] Added GNTL_MOBILE_REQUIRE_AUTH=1 to .env"
    fi
  fi

  if [ -f "$ENV_FILE" ]; then
    set -a
    . "$ENV_FILE"
    set +a
  fi
}

refresh_runtime_config_from_env() {
  MOBILE_PHP_PORT="${GNTL_MOBILE_PHP_PORT:-2027}"
  MOBILE_USE_CADDY="${GNTL_MOBILE_USE_CADDY:-1}"
  PHP_BIN="${GNTL_PHP_BIN:-}"
  FRONTEND_DEV_PORT="${GNTL_FRONTEND_PORT:-5173}"
  BIND_HOST="${GNTL_BIND_HOST:-0.0.0.0}"
  FRONTEND_DEV_HOST="${GNTL_FRONTEND_HOST:-0.0.0.0}"
  AUTO_OPEN_APP="${GNTL_AUTO_OPEN_APP:-1}"
  NODE_MIN_MAJOR="${GNTL_NODE_MIN_MAJOR:-18}"
  NODE_INSTALL_MAJOR="${GNTL_NODE_INSTALL_MAJOR:-20}"
  NODE_LOCAL_INSTALL="${GNTL_NODE_LOCAL_INSTALL:-0}"
  ENABLE_TUNNELS="${GNTL_ENABLE_TUNNELS:-1}"
}

ensure_and_load_env_defaults
refresh_runtime_config_from_env

open_local_app_url() {
  local url="$1"
  local attempt="${2:-1}"
  local auto_open_raw
  auto_open_raw="$(printf '%s' "$AUTO_OPEN_APP" | tr '[:upper:]' '[:lower:]')"
  if ! [[ "$auto_open_raw" =~ ^(1|true|yes|on)$ ]]; then
    return 0
  fi

  if [ -z "$url" ]; then
    return 0
  fi

  try_open_url_command() {
    local cmd="$1"
    shift
    if ! command -v "$cmd" >/dev/null 2>&1; then
      return 1
    fi
    "$cmd" "$@" >/dev/null 2>&1
  }

  if is_termux; then
    if try_open_url_command termux-open-url "$url"; then
      err "[open] Opened via termux-open-url: $url"
      return 0
    fi
    if try_open_url_command termux-open "$url"; then
      err "[open] Opened via termux-open: $url"
      return 0
    fi
    if command -v am >/dev/null 2>&1 && am start -a android.intent.action.VIEW -d "$url" >/dev/null 2>&1; then
      err "[open] Opened via Android intent (am): $url"
      return 0
    fi
  fi

  if try_open_url_command xdg-open "$url"; then
    err "[open] Opened via xdg-open: $url"
    return 0
  fi

  if try_open_url_command open "$url"; then
    err "[open] Opened via open: $url"
    return 0
  fi

  if [ "$attempt" = "1" ]; then
    err "[open] Initial browser open failed; retrying in 2s..."
    (sleep 2; open_local_app_url "$url" 2) >/dev/null 2>&1 &
    return 0
  fi

  if is_termux; then
    err "[open] Could not auto-open browser in Termux. Install/enable termux-tools and optionally Termux:API, then open manually: $url"
    return 0
  fi

  err "[open] No browser opener found. Open manually: $url"
  return 0
}

detect_lan_ip() {
  local ip=""
  if command -v hostname >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  fi
  if [ -z "$ip" ] && command -v ip >/dev/null 2>&1; then
    ip="$(ip route get 1.1.1.1 2>/dev/null | awk '/src/ {for(i=1;i<=NF;i++){if($i=="src"){print $(i+1); exit}}}')"
  fi
  printf '%s' "$ip"
}

# A LAN client that gets ERR_ADDRESS_UNREACHABLE / "no route to host" on a port
# the server is listening on is almost always hitting a firewall REJECT rule.
# Detect the firewall in use and print the exact command to open the ports; never
# change firewall rules automatically.
lan_firewall_hint() {
  local ports="$*"
  local port firewall=""

  if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet firewalld 2>/dev/null; then
    firewall="firewalld"
  fi

  # ufw.service is active on stock Ubuntu even when the firewall is off, so
  # ufw.conf (world-readable) is the authority, not the unit state.
  if [ -z "$firewall" ] && command -v ufw >/dev/null 2>&1; then
    if grep -qi '^ENABLED=yes' /etc/ufw/ufw.conf 2>/dev/null; then
      firewall="ufw"
    elif [ ! -r /etc/ufw/ufw.conf ] && command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet ufw 2>/dev/null; then
      firewall="ufw"
    fi
  fi

  if [ -z "$firewall" ] && [ "$(id -u)" -eq 0 ] && command -v iptables >/dev/null 2>&1; then
    if iptables -S INPUT 2>/dev/null | grep -qE -- '-j (REJECT|DROP)'; then
      firewall="iptables"
    fi
  fi

  if [ -z "$firewall" ] && [ -d /etc/webmin ]; then
    firewall="webmin"
  fi

  [ -n "$firewall" ] || return 0

  err "[net] ${firewall} is active. If a phone/laptop on the LAN reports the address is unreachable, open the ports:"
  case "$firewall" in
    firewalld)
      for port in $ports; do
        err "[net]   sudo firewall-cmd --permanent --add-port=${port}/tcp"
      done
      err "[net]   sudo firewall-cmd --reload"
      ;;
    ufw)
      for port in $ports; do
        err "[net]   sudo ufw allow ${port}/tcp"
      done
      ;;
    iptables)
      for port in $ports; do
        err "[net]   sudo iptables -I INPUT -p tcp --dport ${port} -j ACCEPT"
      done
      err "[net]   then persist them (netfilter-persistent save, or via Webmin)"
      ;;
    webmin)
      err "[net]   Webmin -> Networking -> Linux Firewall: allow TCP ${ports// /, }"
      ;;
  esac
}

is_termux() {
  [[ -n "${TERMUX_VERSION:-}" ]] || [[ "${PREFIX:-}" == *"com.termux"* ]] || command -v termux-info >/dev/null 2>&1
}

is_android_kernel() {
  [[ -n "${ANDROID_ROOT:-}" ]] || [[ -n "${ANDROID_DATA:-}" ]] || \
    grep -qi "android" /proc/version 2>/dev/null || \
    (command -v getprop >/dev/null 2>&1 && getprop ro.build.version.release >/dev/null 2>&1)
}

is_ish_ios() {
  [[ -f /etc/alpine-release ]] && grep -qi "ish\|ios" /proc/version 2>/dev/null
}

is_mobile_runtime() {
  is_termux || is_ish_ios || is_android_kernel
}

is_debian_like() {
  if is_mobile_runtime; then
    return 1
  fi
  [ -r /etc/os-release ] && grep -Eqi '^(ID|ID_LIKE)=.*(debian|ubuntu)' /etc/os-release
}

is_ubuntu_host() {
  is_debian_like && grep -Eqi '^(ID|ID_LIKE)=.*ubuntu' /etc/os-release
}

# Run a command as root when possible. Output/prompts stay visible so a sudo
# password request never looks like a hang.
maybe_sudo() {
  if [ "$(id -u)" -eq 0 ]; then
    "$@"
    return $?
  fi
  if command -v sudo >/dev/null 2>&1; then
    err "[host] Requesting sudo for: $*"
    sudo "$@"
    return $?
  fi
  err "[host] Root privileges required but sudo is unavailable: $*"
  return 127
}

node_major_version() {
  local bin raw
  bin="${1:-node}"
  raw="$("$bin" -v 2>/dev/null || true)"
  [ -n "$raw" ] || return 1
  printf '%s' "${raw#v}" | cut -d. -f1
}

node_is_supported() {
  local major
  major="$(node_major_version 2>/dev/null || true)"
  [ -n "$major" ] || return 1
  [ "$major" -ge "$NODE_MIN_MAJOR" ] 2>/dev/null
}

# A previously installed project-local Node, plus nvm/fnm installs that are not
# on PATH for non-login shells: adopt them before concluding Node is missing.
adopt_user_node_install() {
  if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1 && node_is_supported; then
    return 0
  fi

  # A project-local Node only wins when the system cannot supply a usable one.
  local local_major=""
  local_major="$(node_major_version "$LOCAL_NODE_DIR/bin/node" 2>/dev/null || true)"
  if [ -n "$local_major" ] && [ "$local_major" -ge "$NODE_MIN_MAJOR" ] 2>/dev/null; then
    use_local_node && return 0
  fi

  if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
    return 0
  fi

  local nvm_dir candidate
  nvm_dir="${NVM_DIR:-$HOME/.nvm}"
  if [ -s "$nvm_dir/nvm.sh" ]; then
    # shellcheck disable=SC1090,SC1091
    . "$nvm_dir/nvm.sh" >/dev/null 2>&1 || true
    hash -r 2>/dev/null || true
  fi

  if ! command -v node >/dev/null 2>&1 && [ -d "$nvm_dir/versions/node" ]; then
    candidate="$(find "$nvm_dir/versions/node" -maxdepth 2 -type f -name node -perm -u+x 2>/dev/null | sort -V | tail -n1)"
    if [ -n "$candidate" ]; then
      PATH="$(dirname "$candidate"):$PATH"
      export PATH
      hash -r 2>/dev/null || true
    fi
  fi

  if ! command -v node >/dev/null 2>&1 && [ -x "$HOME/.local/share/fnm/aliases/default/bin/node" ]; then
    PATH="$HOME/.local/share/fnm/aliases/default/bin:$PATH"
    export PATH
    hash -r 2>/dev/null || true
  fi

  command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1
}

find_php_bin() {
  if [ -n "${GNTL_PHP_BIN:-}" ]; then
    if command -v "$GNTL_PHP_BIN" >/dev/null 2>&1; then
      command -v "$GNTL_PHP_BIN"
      return 0
    fi
    if [ -x "$GNTL_PHP_BIN" ]; then
      echo "$GNTL_PHP_BIN"
      return 0
    fi
    err "[mobile] GNTL_PHP_BIN is set but not executable/found: $GNTL_PHP_BIN"
  fi
  local candidate
  for candidate in php php84 php83 php82 php81; do
    if command -v "$candidate" >/dev/null 2>&1; then
      command -v "$candidate"
      return 0
    fi
  done
  return 1
}

ensure_mobile_packages() {
  PHP_BIN="$(find_php_bin || true)"
  if is_termux; then
    if [ -z "$PHP_BIN" ]; then
      err "[mobile] Installing PHP + SQLite runtime in Termux..."
      pkg update -y && pkg install -y php sqlite caddy || true
      PHP_BIN="$(find_php_bin || true)"
    fi
  elif is_ish_ios; then
    if [ -z "$PHP_BIN" ]; then
      err "[mobile] Installing PHP + SQLite runtime in iSH..."
      apk update && apk add php84 php84-session php84-pdo_sqlite php84-sqlite3 sqlite caddy || true
      PHP_BIN="$(find_php_bin || true)"
    fi
  fi
}

detect_frp_arch() {
  local machine
  machine="$(uname -m 2>/dev/null || echo unknown)"
  case "$machine" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    armv7*|armv6*|arm) echo "arm" ;;
    i386|i486|i586|i686|x86) echo "386" ;;
    *) echo "" ;;
  esac
}

is_frpc_usable() {
  local bin="$1"
  if [ ! -x "$bin" ]; then
    return 1
  fi
  if "$bin" -v >/dev/null 2>&1; then
    return 0
  fi
  if "$bin" --version >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

frpc_version_string() {
  local bin="$1"
  local out=""
  out="$($bin -v 2>/dev/null || true)"
  if [ -z "$out" ]; then
    out="$($bin --version 2>/dev/null || true)"
  fi
  if [ -z "$out" ]; then
    out="unknown"
  fi
  printf '%s' "$out"
}

frpc_semver() {
  local bin="$1"
  local raw ver
  raw="$(frpc_version_string "$bin")"
  ver="$(printf '%s' "$raw" | sed -nE 's/.*v?([0-9]+\.[0-9]+\.[0-9]+).*/\1/p' | head -n1)"
  printf '%s' "$ver"
}

frpc_matches_target_version() {
  local bin="$1"
  local target="$2"
  local actual=""
  if [ -z "$target" ]; then
    return 0
  fi
  target="${target#v}"
  actual="$(frpc_semver "$bin")"
  [ -n "$actual" ] && [ "$actual" = "$target" ]
}

download_frpc_release_binary() {
  local arch version asset url tmp_archive tmp_dir found
  arch="$(detect_frp_arch)"
  if [ -z "$arch" ]; then
    err "[$TUNNEL_TAG] Unsupported CPU architecture for FRP download: $(uname -m 2>/dev/null || echo unknown)"
    return 1
  fi

  version="${GNTL_FRP_VERSION:-0.67.0}"
  asset="frp_${version}_linux_${arch}.tar.gz"
  url="https://github.com/fatedier/frp/releases/download/v${version}/${asset}"

  tmp_archive="$(mktemp /tmp/gntl-frp-XXXXXX.tar.gz 2>/dev/null || echo /tmp/gntl-frp-${version}-${arch}.tar.gz)"
  tmp_dir="$(mktemp -d /tmp/gntl-frp-extract-XXXXXX 2>/dev/null || echo /tmp/gntl-frp-extract-${version}-${arch})"

  err "[$TUNNEL_TAG] Downloading FRP client for arch=${arch}: ${asset}"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "$tmp_archive" || return 1
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$tmp_archive" "$url" || return 1
  else
    err "[$TUNNEL_TAG] curl/wget missing; cannot download FRP release."
    return 1
  fi

  mkdir -p "$tmp_dir"
  tar -xzf "$tmp_archive" -C "$tmp_dir" || return 1
  found="$(find "$tmp_dir" -type f -name frpc 2>/dev/null | head -n 1)"
  if [ -z "$found" ] || [ ! -f "$found" ]; then
    err "[$TUNNEL_TAG] Downloaded FRP archive did not contain frpc binary."
    return 1
  fi

  mkdir -p "$(dirname "$FRPC_BIN")"
  cp -f "$found" "$FRPC_BIN"
  chmod +x "$FRPC_BIN" >/dev/null 2>&1 || true
  err "[$TUNNEL_TAG] Installed frpc from release: $(frpc_version_string "$FRPC_BIN")"
  rm -f "$tmp_archive" >/dev/null 2>&1 || true
  rm -rf "$tmp_dir" >/dev/null 2>&1 || true
  return 0
}

ensure_frpc_binary() {
  local target_version
  target_version="${GNTL_FRP_VERSION:-0.67.0}"
  target_version="${target_version#v}"

  mkdir -p "$(dirname "$FRPC_BIN")"
  if is_frpc_usable "$FRPC_BIN"; then
    if frpc_matches_target_version "$FRPC_BIN" "$target_version"; then
      err "[$TUNNEL_TAG] Using existing frpc: $FRPC_BIN ($(frpc_version_string "$FRPC_BIN"))"
      return 0
    fi
    err "[$TUNNEL_TAG] Existing frpc version mismatch; expected ${target_version}, got $(frpc_version_string "$FRPC_BIN"). Re-acquiring binary."
    rm -f "$FRPC_BIN" >/dev/null 2>&1 || true
  fi
  if [ -e "$FRPC_BIN" ]; then
    err "[$TUNNEL_TAG] Existing frpc is not usable on this device; re-acquiring binary."
    rm -f "$FRPC_BIN" >/dev/null 2>&1 || true
  fi

  if command -v frpc >/dev/null 2>&1 && is_frpc_usable "$(command -v frpc)" && frpc_matches_target_version "$(command -v frpc)" "$target_version"; then
    err "[$TUNNEL_TAG] Found matching system frpc (${target_version}) at $(command -v frpc); copying to project bin."
    cp -f "$(command -v frpc)" "$FRPC_BIN" >/dev/null 2>&1 || ln -sf "$(command -v frpc)" "$FRPC_BIN" >/dev/null 2>&1 || true
    chmod +x "$FRPC_BIN" >/dev/null 2>&1 || true
    if is_frpc_usable "$FRPC_BIN"; then
      err "[$TUNNEL_TAG] Using system frpc: $(frpc_version_string "$FRPC_BIN")"
      return 0
    fi
  elif command -v frpc >/dev/null 2>&1 && is_frpc_usable "$(command -v frpc)"; then
    err "[$TUNNEL_TAG] System frpc version does not match ${target_version}: $(frpc_version_string "$(command -v frpc)")"
  fi

  if is_termux; then
    err "[$TUNNEL_TAG] Attempting Termux package install for FRP..."
    pkg install -y frp >/dev/null 2>&1 || true
  elif is_ish_ios; then
    err "[$TUNNEL_TAG] Attempting iSH package install for FRP..."
    apk add frp >/dev/null 2>&1 || true
  fi

  if command -v frpc >/dev/null 2>&1 && is_frpc_usable "$(command -v frpc)" && frpc_matches_target_version "$(command -v frpc)" "$target_version"; then
    err "[$TUNNEL_TAG] Using package-manager frpc from $(command -v frpc)."
    cp -f "$(command -v frpc)" "$FRPC_BIN" >/dev/null 2>&1 || ln -sf "$(command -v frpc)" "$FRPC_BIN" >/dev/null 2>&1 || true
    chmod +x "$FRPC_BIN" >/dev/null 2>&1 || true
    if is_frpc_usable "$FRPC_BIN"; then
      err "[$TUNNEL_TAG] Installed frpc from package manager: $(frpc_version_string "$FRPC_BIN")"
      return 0
    fi
  elif command -v frpc >/dev/null 2>&1 && is_frpc_usable "$(command -v frpc)"; then
    err "[$TUNNEL_TAG] Package-manager frpc version mismatch; expected ${target_version}, got $(frpc_version_string "$(command -v frpc)")."
  fi

  download_frpc_release_binary || return 1
  if ! is_frpc_usable "$FRPC_BIN"; then
    return 1
  fi
  if ! frpc_matches_target_version "$FRPC_BIN" "$target_version"; then
    err "[$TUNNEL_TAG] Downloaded frpc version mismatch; expected ${target_version}, got $(frpc_version_string "$FRPC_BIN")"
    return 1
  fi
  err "[$TUNNEL_TAG] Ready frpc binary: $FRPC_BIN ($(frpc_version_string "$FRPC_BIN"))"
  return 0
}

stop_frpc_instances() {
  local pid_file pid
  shopt -s nullglob
  for pid_file in "$FRPC_PID_DIR"/.gntl-frpc-*.pid; do
    pid=$(cat "$pid_file" 2>/dev/null || true)
    if [ -n "$pid" ] && kill -0 "$pid" >/dev/null 2>&1; then
      kill "$pid" >/dev/null 2>&1 || true
      sleep 0.1
      kill -9 "$pid" >/dev/null 2>&1 || true
    fi
    rm -f "$pid_file" || true
  done
  shopt -u nullglob
}

# Emit "<instance id>\t<config path>" for every enabled instance in the state
# file. PHP is the mobile runtime's parser; desktop hosts (Ubuntu et al.) rarely
# have php-cli, so fall back to python3.
read_enabled_frpc_instances() {
  local php_cmd="${PHP_BIN:-}"
  if [ -z "$php_cmd" ]; then
    php_cmd="$(find_php_bin || true)"
  fi

  if [ -n "$php_cmd" ]; then
    "$php_cmd" -r '
      $f = $argv[1] ?? "";
      if (!$f || !is_file($f)) exit(0);
      $raw = @file_get_contents($f);
      if ($raw === false) exit(0);
      $data = @json_decode($raw, true);
      if (!is_array($data)) exit(0);
      foreach ($data as $id => $entry) {
        if (!is_array($entry)) continue;
        $cfg = $entry["config_path"] ?? "";
        $meta = $entry["metadata"] ?? [];
        $enabled = true;
        if (is_array($meta) && array_key_exists("enabled", $meta)) $enabled = (bool)$meta["enabled"];
        if (!$enabled) continue;
        if (!is_string($cfg) || $cfg === "") continue;
        echo $id . "\t" . $cfg . "\n";
      }
    ' "$FRPC_STATE_FILE"
    return 0
  fi

  local py_cmd=""
  if command -v python3 >/dev/null 2>&1; then
    py_cmd="python3"
  elif command -v python >/dev/null 2>&1; then
    py_cmd="python"
  fi

  if [ -z "$py_cmd" ]; then
    err "[$TUNNEL_TAG] Neither PHP nor Python available to read FRPC state; skipping FRPC autostart."
    return 1
  fi

  "$py_cmd" - "$FRPC_STATE_FILE" <<'PYEOF'
import json, sys

path = sys.argv[1] if len(sys.argv) > 1 else ""
try:
    with open(path, "r", encoding="utf-8") as handle:
        data = json.load(handle)
except Exception:
    sys.exit(0)

if not isinstance(data, dict):
    sys.exit(0)

for inst_id, entry in data.items():
    if not isinstance(entry, dict):
        continue
    cfg = entry.get("config_path") or ""
    meta = entry.get("metadata")
    enabled = True
    if isinstance(meta, dict) and "enabled" in meta:
        enabled = bool(meta["enabled"])
    if not enabled or not isinstance(cfg, str) or not cfg:
        continue
    print("%s\t%s" % (inst_id, cfg))
PYEOF
}

start_frpc_instances() {
  mkdir -p "$MOBILE_LOG_DIR" "$FRPC_PID_DIR"

  if [ ! -f "$FRPC_STATE_FILE" ]; then
    err "[$TUNNEL_TAG] No FRPC state file found; skipping FRPC autostart."
    return 0
  fi

  if [ ! -f "$FRPC_BIN" ]; then
    err "[$TUNNEL_TAG] FRPC binary not found at $FRPC_BIN; skipping FRPC autostart."
    return 0
  fi

  chmod +x "$FRPC_BIN" >/dev/null 2>&1 || true
  if [ ! -x "$FRPC_BIN" ]; then
    err "[$TUNNEL_TAG] FRPC binary is not executable; skipping FRPC autostart."
    return 0
  fi

  stop_frpc_instances

  local entries
  entries="$(read_enabled_frpc_instances || true)"

  printf '%s\n' "$entries" | while IFS=$'\t' read -r inst_id cfg_path; do
    [ -n "$inst_id" ] || continue
    [ -n "$cfg_path" ] || continue
    if [ ! -f "$cfg_path" ]; then
      err "[$TUNNEL_TAG] Missing FRPC config for $inst_id: $cfg_path"
      continue
    fi

    safe_id=$(printf '%s' "$inst_id" | tr -c 'A-Za-z0-9._-' '_')
    pid_file="$FRPC_PID_DIR/.gntl-frpc-${safe_id}.pid"
    log_file="$MOBILE_LOG_DIR/frpc-${safe_id}.log"

    err "[$TUNNEL_TAG] Starting FRPC instance: $inst_id"
    "$FRPC_BIN" -c "$cfg_path" >"$log_file" 2>&1 &
    frpc_pid=$!
    echo "$frpc_pid" > "$pid_file"
  done
}

run_mobile_server() {
  ensure_mobile_packages
  mkdir -p "$MOBILE_LOG_DIR"

  if [ -z "${PHP_BIN:-}" ]; then
    PHP_BIN="$(find_php_bin || true)"
  fi

  if [ -z "$PHP_BIN" ]; then
    err "[mobile] PHP not found after install attempt."
    err "[mobile] Termux: pkg install php sqlite"
    err "[mobile] iSH: apk add php84 php84-session php84-pdo_sqlite php84-sqlite3 sqlite (binary: php84)"
    exit 1
  fi

  if [ ! -f "$MOBILE_ROUTER" ]; then
    err "[mobile] Missing mobile app router: $MOBILE_ROUTER"
    exit 1
  fi

  if ! ensure_frpc_binary; then
    err "[mobile] Could not ensure FRPC binary for this device."
    err "[mobile] Set GNTL_FRP_VERSION if you need a specific release (default: 0.67.0)."
  fi

  stop_previous_instance
  start_frpc_instances

  if [ "$MOBILE_USE_CADDY" = "1" ] && command -v caddy >/dev/null 2>&1; then
    err "[mobile] Starting PHP app on 127.0.0.1:$MOBILE_PHP_PORT"
    PHP_CLI_SERVER_WORKERS="${PHP_CLI_SERVER_WORKERS:-4}" "$PHP_BIN" -S "127.0.0.1:$MOBILE_PHP_PORT" -t "$MOBILE_DOCROOT" "$MOBILE_ROUTER" >"$MOBILE_LOG_DIR/gntl-mobile-php.log" 2>&1 &
    PHP_PID=$!

    CADDY_FILE="$ROOT_DIR/configs/mobile.Caddyfile"
    mkdir -p "$ROOT_DIR/configs"
    cat > "$CADDY_FILE" <<EOF
:2026 {
  reverse_proxy 127.0.0.1:$MOBILE_PHP_PORT {
    flush_interval -1
  }
}
EOF

    err "[mobile] Starting Caddy on http://127.0.0.1:2026"
    caddy run --config "$CADDY_FILE" --adapter caddyfile >"$MOBILE_LOG_DIR/gntl-mobile-caddy.log" 2>&1 &
    SERVER_PID=$!
    sleep 1
    if ! kill -0 "$SERVER_PID" >/dev/null 2>&1; then
      err "[mobile] Caddy failed to start (permission or execution issue). Falling back to direct PHP on 127.0.0.1:2026"
      kill "$PHP_PID" >/dev/null 2>&1 || true
      PHP_CLI_SERVER_WORKERS="${PHP_CLI_SERVER_WORKERS:-4}" "$PHP_BIN" -S "127.0.0.1:2026" -t "$MOBILE_DOCROOT" "$MOBILE_ROUTER" >"$MOBILE_LOG_DIR/gntl-mobile-php.log" 2>&1 &
      SERVER_PID=$!
    fi
    echo "$SERVER_PID" > "$PID_FILE"
    if kill -0 "$SERVER_PID" >/dev/null 2>&1; then
      open_local_app_url "http://127.0.0.1:2026"
    fi

    cleanup() {
      rm -f "$PID_FILE" || true
      kill "$PHP_PID" >/dev/null 2>&1 || true
      stop_frpc_instances
    }

    trap cleanup EXIT INT TERM
    wait "$SERVER_PID"
  else
    if [ "$MOBILE_USE_CADDY" = "1" ]; then
      err "[mobile] Caddy requested but not found; starting PHP server directly on http://127.0.0.1:2026"
    else
      err "[mobile] Starting stable direct PHP mode on http://127.0.0.1:2026 (set GNTL_MOBILE_USE_CADDY=1 to enable Caddy)"
    fi
    PHP_CLI_SERVER_WORKERS="${PHP_CLI_SERVER_WORKERS:-4}" "$PHP_BIN" -S "127.0.0.1:2026" -t "$MOBILE_DOCROOT" "$MOBILE_ROUTER" >"$MOBILE_LOG_DIR/gntl-mobile-php.log" 2>&1 &
    SERVER_PID=$!
    echo "$SERVER_PID" > "$PID_FILE"
    if kill -0 "$SERVER_PID" >/dev/null 2>&1; then
      open_local_app_url "http://127.0.0.1:2026"
    fi

    cleanup() {
      rm -f "$PID_FILE" || true
      stop_frpc_instances
    }

    trap cleanup EXIT INT TERM
    wait "$SERVER_PID"
  fi
}

# Install everything the desktop stack needs on Debian/Ubuntu hosts: build/run
# prerequisites for the Python backend, Node LTS for the frontend, and the frpc
# tunnel client.
bootstrap_ubuntu_host() {
  if is_mobile_runtime; then
    err "[host] Mobile runtime detected; skipping Ubuntu host bootstrap."
    return 0
  fi

  if ! command -v apt-get >/dev/null 2>&1; then
    err "[host] 'ubuntu' mode requires apt-get; this host does not have it."
    err "[host] Continuing with the generic setup path."
    return 0
  fi

  err "[host] Preparing Ubuntu/Debian host prerequisites (may prompt for sudo)..."
  maybe_sudo apt-get update -y || true
  maybe_sudo apt-get install -y \
    ca-certificates curl wget tar gzip openssl \
    python3 python3-venv python3-pip \
    sqlite3 || err "[host] Some apt packages could not be installed; continuing."

  ensure_host_node_runtime

  TUNNEL_TAG="tunnel"
  if ! ensure_frpc_binary; then
    err "[tunnel] Could not install the frpc client during host bootstrap."
    err "[tunnel] Set GNTL_FRP_VERSION to pick a specific release (default: 0.67.0)."
  fi

  err "[host] Ubuntu host bootstrap complete."
}

GNTL_SERVICE_NAME="gntl.service"
GNTL_SERVICE_PATH="/etc/systemd/system/$GNTL_SERVICE_NAME"

# Survive reboots. The manager auto-starts every enabled tunnel when it comes
# up, so keeping the manager alive is all that persistence requires.
install_manager_service() {
  if ! command -v systemctl >/dev/null 2>&1; then
    err "[service] systemd not available on this host; cannot install a boot service."
    err "[service] Start gntl from your own supervisor or add ./run.sh to a startup script."
    return 1
  fi

  local run_user venv_py
  run_user="${SUDO_USER:-$(id -un)}"
  venv_py="$VENV_DIR/bin/python"
  if [ ! -x "$venv_py" ]; then
    err "[service] No virtualenv yet at $venv_py; run ./run.sh once first."
    return 1
  fi

  err "[service] Installing $GNTL_SERVICE_NAME (user: $run_user, root: $ROOT_DIR)"
  local unit
  unit="$(cat <<EOF
[Unit]
Description=Ginto Tunnel (gntl) manager
Documentation=https://github.com/oliverbob/gntl
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$run_user
WorkingDirectory=$ROOT_DIR
EnvironmentFile=-$ROOT_DIR/.env
Environment=PYTHONPATH=$BACKEND_SRC_DIR
ExecStart=$venv_py -m gntl.main
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
)"

  if [ "$(id -u)" -eq 0 ]; then
    printf '%s\n' "$unit" > "$GNTL_SERVICE_PATH"
  elif command -v sudo >/dev/null 2>&1; then
    err "[service] Writing $GNTL_SERVICE_PATH (sudo)"
    printf '%s\n' "$unit" | sudo tee "$GNTL_SERVICE_PATH" >/dev/null
  else
    err "[service] Root privileges required to write $GNTL_SERVICE_PATH"
    return 1
  fi

  maybe_sudo systemctl daemon-reload || true
  maybe_sudo systemctl enable "$GNTL_SERVICE_NAME" || true

  # The manager binds 2026/2027; a foreground copy would fight the service.
  stop_previous_instance
  maybe_sudo systemctl restart "$GNTL_SERVICE_NAME" || true

  err "[service] Installed and enabled. Tunnels now come back after a reboot."
  err "[service]   status:  systemctl status $GNTL_SERVICE_NAME"
  err "[service]   logs:    journalctl -u $GNTL_SERVICE_NAME -f"
  err "[service]   disable: ./run.sh uninstall-service"
  return 0
}

uninstall_manager_service() {
  if ! command -v systemctl >/dev/null 2>&1; then
    err "[service] systemd not available; nothing to remove."
    return 0
  fi
  maybe_sudo systemctl disable --now "$GNTL_SERVICE_NAME" || true
  if [ -f "$GNTL_SERVICE_PATH" ]; then
    maybe_sudo rm -f "$GNTL_SERVICE_PATH" || true
  fi
  maybe_sudo systemctl daemon-reload || true
  err "[service] Removed $GNTL_SERVICE_NAME. gntl no longer starts at boot."
  return 0
}

# Desktop hosts let the Python backend own tunnel lifecycle (it auto-starts every
# enabled instance at boot), so run.sh only has to guarantee that a matching frpc
# binary is present before the backend looks for one.
prepare_desktop_tunnels() {
  if [ "$ENABLE_TUNNELS" != "1" ]; then
    err "[tunnel] Tunnel preparation disabled (--no-tunnels / GNTL_ENABLE_TUNNELS=0)."
    return 0
  fi

  TUNNEL_TAG="tunnel"
  mkdir -p "$MOBILE_LOG_DIR" "$FRPC_PID_DIR"

  if ! ensure_frpc_binary; then
    err "[tunnel] frpc client unavailable; tunnels will stay offline until it is installed."
    if is_ubuntu_host; then
      err "[tunnel] Retry with network access, or run: ./run.sh ubuntu"
    else
      err "[tunnel] Retry with network access, or place an frpc binary at $FRPC_BIN"
    fi
    return 1
  fi

  if [ ! -f "$FRPC_STATE_FILE" ]; then
    err "[tunnel] No tunnel instances configured yet; create one from the web admin UI."
    return 0
  fi

  local entries configured
  entries="$(read_enabled_frpc_instances || true)"
  configured="$(printf '%s' "$entries" | grep -c . || true)"
  if [ "${configured:-0}" -gt 0 ]; then
    err "[tunnel] ${configured} enabled tunnel instance(s) found; the backend will auto-start them."
  else
    err "[tunnel] No enabled tunnel instances in $FRPC_STATE_FILE."
  fi
  return 0
}

ensure_frontend_runtime() {
  ensure_mobile_node_runtime
  ensure_host_node_runtime

  if [ ! -d "$FRONTEND_DIR" ]; then
    err "[frontend] Missing frontend directory: $FRONTEND_DIR"
    exit 1
  fi
  if ! command -v npm >/dev/null 2>&1; then
    err "[frontend] npm is required. Install Node.js/npm first."
    exit 1
  fi
  if [ ! -f "$FRONTEND_DIR/package.json" ]; then
    err "[frontend] Missing package.json in $FRONTEND_DIR"
    exit 1
  fi
}

node_platform_arch() {
  case "$(uname -m 2>/dev/null || echo unknown)" in
    x86_64|amd64) echo "x64" ;;
    aarch64|arm64) echo "arm64" ;;
    armv7l|armv7*) echo "armv7l" ;;
    ppc64le) echo "ppc64le" ;;
    s390x) echo "s390x" ;;
    *) echo "" ;;
  esac
}

# Install the official Node.js build into the project (no root, no apt). This is
# the safe path on managed hosts such as Virtualmin/cPanel servers, where the
# distro npm package conflicts with NodeSource nodejs and apt refuses both.
install_node_local() {
  local arch tarball url tmp_archive tmp_dir extracted os_name
  arch="$(node_platform_arch)"
  if [ -z "$arch" ]; then
    err "[frontend] Unsupported CPU architecture for a local Node.js install: $(uname -m 2>/dev/null || echo unknown)"
    return 1
  fi

  os_name="linux"
  case "$(uname -s 2>/dev/null || echo Linux)" in
    Darwin*) os_name="darwin" ;;
  esac

  if ! command -v curl >/dev/null 2>&1 && ! command -v wget >/dev/null 2>&1; then
    err "[frontend] curl/wget missing; cannot download Node.js."
    return 1
  fi

  err "[frontend] Installing Node.js ${NODE_INSTALL_MAJOR} LTS into $LOCAL_NODE_DIR (no system packages touched)..."

  # SHASUMS256.txt names the exact point release for this line, so no version
  # guessing and no dependency on a JSON parser.
  local shasums=""
  if command -v curl >/dev/null 2>&1; then
    shasums="$(curl -fsSL "https://nodejs.org/dist/latest-v${NODE_INSTALL_MAJOR}.x/SHASUMS256.txt" 2>/dev/null || true)"
  else
    shasums="$(wget -qO- "https://nodejs.org/dist/latest-v${NODE_INSTALL_MAJOR}.x/SHASUMS256.txt" 2>/dev/null || true)"
  fi

  tarball="$(printf '%s\n' "$shasums" | awk '{print $2}' | grep -E "^node-v[0-9.]+-${os_name}-${arch}\.tar\.gz$" | head -n1 || true)"
  if [ -z "$tarball" ]; then
    err "[frontend] Could not resolve a Node.js ${NODE_INSTALL_MAJOR} build for ${os_name}-${arch}."
    return 1
  fi

  url="https://nodejs.org/dist/latest-v${NODE_INSTALL_MAJOR}.x/${tarball}"
  tmp_archive="$(mktemp /tmp/gntl-node-XXXXXX.tar.gz 2>/dev/null || echo "/tmp/${tarball}")"
  tmp_dir="$(mktemp -d /tmp/gntl-node-extract-XXXXXX 2>/dev/null || echo /tmp/gntl-node-extract)"

  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "$tmp_archive" || { rm -rf "$tmp_archive" "$tmp_dir"; return 1; }
  else
    wget -qO "$tmp_archive" "$url" || { rm -rf "$tmp_archive" "$tmp_dir"; return 1; }
  fi

  mkdir -p "$tmp_dir"
  tar -xzf "$tmp_archive" -C "$tmp_dir" || { rm -rf "$tmp_archive" "$tmp_dir"; return 1; }
  extracted="$(find "$tmp_dir" -maxdepth 1 -mindepth 1 -type d -name 'node-v*' | head -n1)"
  if [ -z "$extracted" ] || [ ! -x "$extracted/bin/node" ]; then
    err "[frontend] Downloaded Node.js archive did not contain a usable binary."
    rm -rf "$tmp_archive" "$tmp_dir"
    return 1
  fi

  rm -rf "$LOCAL_NODE_DIR" >/dev/null 2>&1 || true
  mkdir -p "$(dirname "$LOCAL_NODE_DIR")"
  mv "$extracted" "$LOCAL_NODE_DIR" || { rm -rf "$tmp_archive" "$tmp_dir"; return 1; }
  rm -rf "$tmp_archive" "$tmp_dir" >/dev/null 2>&1 || true

  use_local_node || return 1
  err "[frontend] Local Node.js ready: $(node -v 2>/dev/null || echo unknown) at $LOCAL_NODE_DIR"
  return 0
}

use_local_node() {
  [ -x "$LOCAL_NODE_DIR/bin/node" ] && [ -x "$LOCAL_NODE_DIR/bin/npm" ] || return 1
  case ":$PATH:" in
    *":$LOCAL_NODE_DIR/bin:"*) ;;
    *) PATH="$LOCAL_NODE_DIR/bin:$PATH"; export PATH ;;
  esac
  hash -r 2>/dev/null || true
  return 0
}

# Debian/Ubuntu ship Node versions that are frequently older than SvelteKit/Vite
# support, so prefer the NodeSource LTS repository and fall back to the distro
# packages only if that is unavailable.
install_node_debian() {
  local setup_script
  setup_script="$(mktemp /tmp/gntl-nodesource-XXXXXX.sh 2>/dev/null || echo /tmp/gntl-nodesource.sh)"

  if command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1; then
    err "[frontend] Installing Node.js ${NODE_INSTALL_MAJOR}.x LTS from NodeSource (apt)..."
    maybe_sudo apt-get update -y || true
    maybe_sudo apt-get install -y ca-certificates curl gnupg || true

    if command -v curl >/dev/null 2>&1; then
      curl -fsSL "https://deb.nodesource.com/setup_${NODE_INSTALL_MAJOR}.x" -o "$setup_script" || true
    else
      wget -qO "$setup_script" "https://deb.nodesource.com/setup_${NODE_INSTALL_MAJOR}.x" || true
    fi

    if [ -s "$setup_script" ]; then
      maybe_sudo bash "$setup_script" || err "[frontend] NodeSource setup script failed; falling back to distro packages."
      # NodeSource nodejs bundles npm and declares "Conflicts: npm", so npm must
      # never be requested alongside it: apt would reject the whole transaction.
      maybe_sudo apt-get install -y nodejs || true
    fi
    rm -f "$setup_script" >/dev/null 2>&1 || true
  fi

  hash -r 2>/dev/null || true
  if node_is_supported && command -v npm >/dev/null 2>&1; then
    return 0
  fi

  err "[frontend] Falling back to distro Node.js package (apt-get install nodejs)..."
  maybe_sudo apt-get update -y || true
  maybe_sudo apt-get install -y nodejs || true
  hash -r 2>/dev/null || true

  # Distro nodejs (unlike NodeSource) ships without npm; only then is the
  # separate npm package both needed and installable.
  if command -v node >/dev/null 2>&1 && ! command -v npm >/dev/null 2>&1; then
    err "[frontend] node present without npm; installing the npm package..."
    maybe_sudo apt-get install -y npm || err "[frontend] apt could not install npm alongside this nodejs build."
    hash -r 2>/dev/null || true
  fi
}

ensure_host_node_runtime() {
  if is_mobile_runtime; then
    return 0
  fi

  adopt_user_node_install || true

  if command -v npm >/dev/null 2>&1 && node_is_supported; then
    return 0
  fi

  if command -v node >/dev/null 2>&1 && ! node_is_supported; then
    err "[frontend] Node $(node -v 2>/dev/null || echo unknown) is older than the required v${NODE_MIN_MAJOR}; upgrading..."
  else
    err "[frontend] Node.js/npm missing; installing..."
  fi

  # Managed/shared servers: keep the system package set untouched by default.
  if [ "$NODE_LOCAL_INSTALL" = "1" ]; then
    if install_node_local && node_is_supported; then
      return 0
    fi
    err "[frontend] Local Node.js install failed; trying the system package manager..."
  fi

  if [ "$(id -u)" -ne 0 ] && ! command -v sudo >/dev/null 2>&1; then
    err "[frontend] No root privileges available; installing Node.js into the project instead."
    if install_node_local && node_is_supported; then
      return 0
    fi
  fi

  err "[frontend] Package-manager install may prompt for your sudo password."

  if command -v apt-get >/dev/null 2>&1; then
    install_node_debian
  elif command -v dnf >/dev/null 2>&1; then
    maybe_sudo dnf install -y nodejs npm || true
  elif command -v yum >/dev/null 2>&1; then
    maybe_sudo yum install -y nodejs npm || true
  elif command -v pacman >/dev/null 2>&1; then
    maybe_sudo pacman -Syu --noconfirm nodejs npm || true
  elif command -v apk >/dev/null 2>&1; then
    maybe_sudo apk update || true
    maybe_sudo apk add nodejs npm || true
  elif command -v brew >/dev/null 2>&1; then
    brew install node || true
  fi

  hash -r 2>/dev/null || true

  # Any package-manager outcome that is missing, broken, or too old (held
  # packages, npm/nodejs conflicts, ancient distro builds) lands here: fetch the
  # official build into the project rather than fighting the system packages.
  if ! command -v npm >/dev/null 2>&1 || ! node_is_supported; then
    err "[frontend] System packages did not provide a usable Node.js ${NODE_MIN_MAJOR}+ toolchain."
    install_node_local || true
  fi

  if ! command -v npm >/dev/null 2>&1 || ! command -v node >/dev/null 2>&1; then
    err "[frontend] Could not auto-install Node.js/npm on this host."
    if is_debian_like; then
      err "[frontend] Ubuntu/Debian: curl -fsSL https://deb.nodesource.com/setup_${NODE_INSTALL_MAJOR}.x | sudo -E bash - && sudo apt-get install -y nodejs"
      err "[frontend] Do not add 'npm' to that install: NodeSource nodejs bundles npm and conflicts with the distro npm package."
      err "[frontend] If apt reports held/broken packages, clear them first: sudo apt-get -f install"
    fi
    err "[frontend] Then re-run ./run.sh frontend-install"
    exit 1
  fi

  if ! node_is_supported; then
    err "[frontend] Node $(node -v 2>/dev/null || echo unknown) is still below the required v${NODE_MIN_MAJOR}."
    err "[frontend] Install Node ${NODE_INSTALL_MAJOR} LTS (NodeSource or nvm) and re-run ./run.sh frontend-install"
    exit 1
  fi

  err "[frontend] Using node: $(command -v node) ($(node -v 2>/dev/null || echo unknown))"
  err "[frontend] Using npm: $(command -v npm) ($(npm -v 2>/dev/null || echo unknown))"
}

ensure_mobile_node_runtime() {
  if ! is_mobile_runtime; then
    return 0
  fi

  if command -v npm >/dev/null 2>&1 && command -v node >/dev/null 2>&1; then
    return 0
  fi

  if is_termux; then
    err "[frontend] Mobile runtime detected (Termux). Installing Node.js + npm..."
    pkg update -y >/dev/null 2>&1 || true
    pkg install -y termux-tools >/dev/null 2>&1 || true

    pkg install -y nodejs-lts >/dev/null 2>&1 || true
    if ! command -v node >/dev/null 2>&1 && ! command -v nodejs >/dev/null 2>&1; then
      pkg install -y tur-repo >/dev/null 2>&1 || true
      pkg install -y nodejs-lts >/dev/null 2>&1 || true
      pkg install -y nodejs-current >/dev/null 2>&1 || true
      pkg install -y nodejs >/dev/null 2>&1 || true
    fi

    if ! command -v npm >/dev/null 2>&1; then
      pkg install -y npm >/dev/null 2>&1 || true
      hash -r 2>/dev/null || true
    fi

    if ! command -v node >/dev/null 2>&1 && command -v nodejs >/dev/null 2>&1; then
      ln -sf "$(command -v nodejs)" "$PREFIX/bin/node" >/dev/null 2>&1 || true
      hash -r 2>/dev/null || true
    fi

    if { ! command -v node >/dev/null 2>&1 && ! command -v nodejs >/dev/null 2>&1; } || ! command -v npm >/dev/null 2>&1; then
      err "[frontend] Initial Termux Node/npm install incomplete; attempting reinstall..."
      pkg reinstall -y nodejs-lts npm >/dev/null 2>&1 || pkg reinstall -y nodejs npm >/dev/null 2>&1 || true
      hash -r 2>/dev/null || true
      if ! command -v node >/dev/null 2>&1 && command -v nodejs >/dev/null 2>&1; then
        ln -sf "$(command -v nodejs)" "$PREFIX/bin/node" >/dev/null 2>&1 || true
        hash -r 2>/dev/null || true
      fi
    fi
  elif is_ish_ios; then
    err "[frontend] Mobile runtime detected (iSH). Installing Node.js + npm..."
    apk update >/dev/null 2>&1 || true
    apk add nodejs npm >/dev/null 2>&1 || true
  elif is_android_kernel; then
    err "[frontend] Android runtime detected. Attempting Node.js + npm install..."
    if command -v pkg >/dev/null 2>&1; then
      pkg update -y >/dev/null 2>&1 || true
      pkg install -y nodejs-lts >/dev/null 2>&1 || pkg install -y nodejs >/dev/null 2>&1 || true
      if ! command -v npm >/dev/null 2>&1; then
        pkg install -y npm >/dev/null 2>&1 || true
        hash -r 2>/dev/null || true
      fi
    elif command -v apt-get >/dev/null 2>&1; then
      apt-get update >/dev/null 2>&1 || true
      apt-get install -y nodejs npm >/dev/null 2>&1 || true
    elif command -v apk >/dev/null 2>&1; then
      apk update >/dev/null 2>&1 || true
      apk add nodejs npm >/dev/null 2>&1 || true
    elif command -v dnf >/dev/null 2>&1; then
      dnf install -y nodejs npm >/dev/null 2>&1 || true
    elif command -v yum >/dev/null 2>&1; then
      yum install -y nodejs npm >/dev/null 2>&1 || true
    fi
  fi

  if ! command -v node >/dev/null 2>&1 && command -v nodejs >/dev/null 2>&1; then
    hash -r 2>/dev/null || true
  fi

  if ! command -v npm >/dev/null 2>&1 || { ! command -v node >/dev/null 2>&1 && ! command -v nodejs >/dev/null 2>&1; }; then
    err "[frontend] Node.js/npm not available after mobile install attempt."
    err "[frontend] Termux: run 'pkg install nodejs-lts npm'"
    err "[frontend] Android (non-Termux): install via your shell package manager (apt/apk/dnf/yum)."
    err "[frontend] iSH: run 'apk add nodejs npm'"
    exit 1
  fi

  if command -v node >/dev/null 2>&1; then
    err "[frontend] Using node: $(command -v node) ($(node -v 2>/dev/null || echo unknown))"
  else
    err "[frontend] Using nodejs: $(command -v nodejs) ($(nodejs -v 2>/dev/null || echo unknown))"
  fi
  err "[frontend] Using npm: $(command -v npm) ($(npm -v 2>/dev/null || echo unknown))"

  if is_termux; then
    mkdir -p "$ROOT_DIR/configs/.npm-cache" "$HOME/.npm" >/dev/null 2>&1 || true
    export NPM_CONFIG_CACHE="$ROOT_DIR/configs/.npm-cache"
    export npm_config_cache="$ROOT_DIR/configs/.npm-cache"
    export npm_config_audit="false"
    export npm_config_fund="false"
    export npm_config_optional="false"
    export npm_config_update_notifier="false"
  fi
}

detect_frontend_api_target() {
  local https_target http_target probe_path
  https_target="https://127.0.0.1:2026"
  http_target="http://127.0.0.1:2026"
  probe_path="/_status"

  if command -v curl >/dev/null 2>&1; then
    if curl -kfsS "${https_target}${probe_path}" >/dev/null 2>&1; then
      printf '%s' "$https_target"
      return 0
    fi
    if curl -fsS "${http_target}${probe_path}" >/dev/null 2>&1; then
      printf '%s' "$http_target"
      return 0
    fi
  fi

  printf '%s' "$https_target"
}

frontend_env_prefix() {
  local target
  target="${GNTL_API_TARGET:-}"
  if [ -z "$target" ]; then
    target="$(detect_frontend_api_target)"
  fi
  printf 'GNTL_API_TARGET=%q VITE_GNTL_API_BASE=%q GNTL_FRONTEND_HOST=%q GNTL_FRONTEND_PORT=%q' "$target" "$target" "$FRONTEND_DEV_HOST" "$FRONTEND_DEV_PORT"
}

hash_file_sha256() {
  local file_path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file_path" | awk '{print $1}'
    return 0
  fi
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$file_path" | awk '{print $1}'
    return 0
  fi
  if command -v openssl >/dev/null 2>&1; then
    openssl dgst -sha256 "$file_path" | awk '{print $NF}'
    return 0
  fi
  return 1
}

hash_stdin_sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
    return 0
  fi
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | awk '{print $1}'
    return 0
  fi
  if command -v openssl >/dev/null 2>&1; then
    openssl dgst -sha256 | awk '{print $NF}'
    return 0
  fi
  return 1
}

compute_frontend_source_hash() {
  local item
  local -a tracked_paths=()
  for item in package.json package-lock.json svelte.config.js vite.config.ts tsconfig.json src; do
    if [ -e "$FRONTEND_DIR/$item" ]; then
      tracked_paths+=("$item")
    fi
  done

  if [ ${#tracked_paths[@]} -eq 0 ]; then
    return 1
  fi

  (
    cd "$FRONTEND_DIR"
    find "${tracked_paths[@]}" -type f -print0 2>/dev/null | sort -z
  ) | while IFS= read -r -d '' rel_path; do
    local full_path file_hash
    full_path="$FRONTEND_DIR/$rel_path"
    file_hash="$(hash_file_sha256 "$full_path" 2>/dev/null || true)"
    if [ -z "$file_hash" ]; then
      return 1
    fi
    printf '%s  %s\n' "$file_hash" "$rel_path"
  done | hash_stdin_sha256
}

frontend_install() {
  ensure_frontend_runtime
  err "[frontend] Installing dependencies via npm..."
  (
    cd "$FRONTEND_DIR"
    npm cache verify >/dev/null 2>&1 || npm cache clean --force >/dev/null 2>&1 || true
    if ! npm install --no-audit --no-fund; then
      err "[frontend] npm install failed; retrying with cleaned lock/cache and optional deps disabled..."
      rm -f package-lock.json >/dev/null 2>&1 || true
      rm -rf node_modules >/dev/null 2>&1 || true
      npm cache clean --force >/dev/null 2>&1 || true
      npm install --no-audit --no-fund --omit=optional
    fi
  )
}

kill_processes_on_port() {
  local port="$1"
  local pids=""
  local pid

  if [ -z "$port" ]; then
    return 0
  fi

  if command -v lsof >/dev/null 2>&1; then
    pids="$(lsof -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)"
  elif command -v fuser >/dev/null 2>&1; then
    pids="$(fuser -n tcp "$port" 2>/dev/null | tr ' ' '\n' || true)"
  fi

  if [ -z "$pids" ]; then
    return 0
  fi

  err "[frontend] Port $port is in use; stopping existing process(es): $(echo "$pids" | tr '\n' ' ' | xargs)"
  for pid in $pids; do
    if [ -n "$pid" ] && kill -0 "$pid" >/dev/null 2>&1; then
      kill "$pid" >/dev/null 2>&1 || true
    fi
  done

  sleep 0.3
  for pid in $pids; do
    if [ -n "$pid" ] && kill -0 "$pid" >/dev/null 2>&1; then
      kill -9 "$pid" >/dev/null 2>&1 || true
    fi
  done
}

frontend_start_no_install() {
  local env_prefix
  local lan_ip
  env_prefix="$(frontend_env_prefix)"
  kill_processes_on_port "$FRONTEND_DEV_PORT"
  err "[frontend] API target: ${GNTL_API_TARGET:-$(detect_frontend_api_target)}"
  err "[frontend] Dev host: $FRONTEND_DEV_HOST"
  err "[frontend] Dev port: $FRONTEND_DEV_PORT"
  err "[frontend] Local URL: http://127.0.0.1:$FRONTEND_DEV_PORT"
  if [ "$FRONTEND_DEV_HOST" = "0.0.0.0" ] || [ "$FRONTEND_DEV_HOST" = "::" ]; then
    lan_ip="$(detect_lan_ip)"
    if [ -n "$lan_ip" ]; then
      err "[frontend] Mobile URL (same Wi‑Fi): http://$lan_ip:$FRONTEND_DEV_PORT"
    fi
  fi
  err "[frontend] Starting SvelteKit dev server..."
  (cd "$FRONTEND_DIR" && eval "$env_prefix npm run start")
}

frontend_build_no_install() {
  local env_prefix
  env_prefix="$(frontend_env_prefix)"
  err "[frontend] API target: ${GNTL_API_TARGET:-$(detect_frontend_api_target)}"
  err "[frontend] Building SvelteKit frontend..."
  (cd "$FRONTEND_DIR" && eval "$env_prefix npm run build")
}

frontend_compile_no_install() {
  local env_prefix
  env_prefix="$(frontend_env_prefix)"
  err "[frontend] API target: ${GNTL_API_TARGET:-$(detect_frontend_api_target)}"
  err "[frontend] Running frontend compile/type checks..."
  (cd "$FRONTEND_DIR" && eval "$env_prefix npm run check")
}

frontend_build_if_changed_no_install() {
  local current_hash previous_hash
  current_hash="$(compute_frontend_source_hash || true)"

  if [ -z "$current_hash" ]; then
    err "[frontend] Could not compute source hash; running build to be safe."
    frontend_build_no_install
    return 0
  fi

  previous_hash=""
  if [ -f "$FRONTEND_BUILD_STAMP" ]; then
    previous_hash="$(cat "$FRONTEND_BUILD_STAMP" 2>/dev/null || true)"
  fi

  if [ -n "$previous_hash" ] && [ "$current_hash" = "$previous_hash" ]; then
    err "[frontend] No detected frontend source/config changes; skipping build."
    return 0
  fi

  err "[frontend] Changes detected; running build before start."
  frontend_build_no_install
  mkdir -p "$(dirname "$FRONTEND_BUILD_STAMP")"
  printf '%s' "$current_hash" > "$FRONTEND_BUILD_STAMP"
}

prepare_frontend_for_backend_serving() {
  frontend_install
  frontend_compile_no_install
  frontend_build_no_install
  err "[frontend] Frontend install + compile + build routines completed."
}

frontend_start() {
  frontend_install
  frontend_start_no_install
}

frontend_build() {
  frontend_install
  frontend_build_no_install
}

TLS_CERT="${GNTL_TLS_CERT:-}"
TLS_KEY="${GNTL_TLS_KEY:-}"
RUN_RESET="0"
RUN_FRONTEND_INSTALL="0"
RUN_FRONTEND_START="0"
RUN_FRONTEND_BUILD="0"
RUN_BACKEND="0"
RUN_INSTALL_SERVICE="0"
RUN_UNINSTALL_SERVICE="0"

while [ $# -gt 0 ]; do
  case "$1" in
    reset|--reset)
      RUN_RESET="1"
      shift
      ;;
    frontend-install|--frontend-install)
      RUN_FRONTEND_INSTALL="1"
      shift
      ;;
    frontend-start|--frontend-start|frontend-dev|--frontend-dev)
      RUN_FRONTEND_START="1"
      shift
      ;;
    frontend-build|--frontend-build)
      RUN_FRONTEND_BUILD="1"
      shift
      ;;
    backend|--backend)
      RUN_BACKEND="1"
      shift
      ;;
    ubuntu|--ubuntu|debian|--debian|linux|--linux)
      UBUNTU_BOOTSTRAP="1"
      shift
      ;;
    install-service|--install-service)
      RUN_INSTALL_SERVICE="1"
      shift
      ;;
    uninstall-service|--uninstall-service)
      RUN_UNINSTALL_SERVICE="1"
      shift
      ;;
    tunnels|--tunnels)
      ENABLE_TUNNELS="1"
      shift
      ;;
    --local-node)
      NODE_LOCAL_INSTALL="1"
      shift
      ;;
    --no-tunnels)
      ENABLE_TUNNELS="0"
      shift
      ;;
    --tls-cert)
      TLS_CERT="${2:-}"
      shift 2
      ;;
    --tls-key)
      TLS_KEY="${2:-}"
      shift 2
      ;;
    *)
      err "Unknown argument: $1"
      err "Usage: ./run.sh [reset] [ubuntu] [install-service|uninstall-service]"
      err "                [frontend-install|frontend-start|frontend-build|backend]"
      err "                [--tunnels|--no-tunnels] [--local-node] [--tls-cert /path/to/cert.pem --tls-key /path/to/key.pem]"
      err "  ubuntu          Install host prerequisites (Node LTS, Python venv tooling, frpc) on Debian/Ubuntu, then run normally."
      err "  install-service Run gntl from systemd so tunnels survive a reboot (uninstall-service to undo)."
      err "  --no-tunnels    Skip frpc tunnel preparation for this run."
      err "  --local-node    Install Node.js into bin/node instead of using system packages (managed servers)."
      exit 1
      ;;
  esac
done

front_ops=$((RUN_FRONTEND_INSTALL + RUN_FRONTEND_START + RUN_FRONTEND_BUILD))
if [ "$front_ops" -gt 1 ]; then
  err "Choose only one frontend command: frontend-install, frontend-start, or frontend-build"
  exit 1
fi

if [ "$RUN_BACKEND" = "1" ] && [ "$front_ops" -gt 0 ]; then
  err "Do not combine backend with frontend commands. Use either backend or one frontend command."
  exit 1
fi

if { [ -n "$TLS_CERT" ] && [ -z "$TLS_KEY" ]; } || { [ -z "$TLS_CERT" ] && [ -n "$TLS_KEY" ]; }; then
  err "Both TLS cert and key are required when enabling TLS."
  err "Set both GNTL_TLS_CERT and GNTL_TLS_KEY, or pass --tls-cert and --tls-key."
  exit 1
fi

if [ -n "$TLS_CERT" ]; then
  export GNTL_TLS_CERT="$TLS_CERT"
  export GNTL_TLS_KEY="$TLS_KEY"
fi

if [ "$UBUNTU_BOOTSTRAP" = "1" ] && [ "$RUN_RESET" != "1" ]; then
  bootstrap_ubuntu_host
fi

ensure_auto_tls() {
  if [ -n "${GNTL_TLS_CERT:-}" ] || [ -n "${GNTL_TLS_KEY:-}" ]; then
    return 0
  fi

  mkdir -p "$TLS_DIR"
  if [ -s "$AUTO_TLS_CERT" ] && [ -s "$AUTO_TLS_KEY" ]; then
    export GNTL_TLS_CERT="$AUTO_TLS_CERT"
    export GNTL_TLS_KEY="$AUTO_TLS_KEY"
    err "Using existing auto-generated TLS cert/key in $TLS_DIR"
    return 0
  fi

  if command -v openssl >/dev/null 2>&1; then
    err "No TLS cert/key provided; generating local self-signed cert automatically..."
    openssl req -x509 -nodes -newkey rsa:2048 \
      -keyout "$AUTO_TLS_KEY" \
      -out "$AUTO_TLS_CERT" \
      -days 365 \
      -subj "/CN=localhost" >/dev/null 2>&1
    chmod 600 "$AUTO_TLS_KEY" || true
    chmod 644 "$AUTO_TLS_CERT" || true
    export GNTL_TLS_CERT="$AUTO_TLS_CERT"
    export GNTL_TLS_KEY="$AUTO_TLS_KEY"
    err "Generated TLS cert/key at $TLS_DIR (self-signed)."
  else
    err "OpenSSL not found; TLS auto-generation skipped. Running without TLS."
  fi
}

terminate_pid() {
  local pid="$1"
  if [ -z "$pid" ]; then
    return 0
  fi
  if ! kill -0 "$pid" >/dev/null 2>&1; then
    return 0
  fi
  err "Stopping previous webadmin process (PID $pid)..."
  kill "$pid" >/dev/null 2>&1 || true
  sleep 1
  if kill -0 "$pid" >/dev/null 2>&1; then
    kill -9 "$pid" >/dev/null 2>&1 || true
  fi
}

stop_previous_instance() {
  if [ -f "$PID_FILE" ]; then
    old_pid=$(cat "$PID_FILE" 2>/dev/null || true)
    terminate_pid "$old_pid"
    rm -f "$PID_FILE" || true
  fi

  old_pids=$(pgrep -f "$APP_ENTRY" || true)
  if [ -n "$old_pids" ]; then
    for pid in $old_pids; do
      if [ "$pid" != "$$" ]; then
        terminate_pid "$pid"
      fi
    done
  fi
}

reset_runtime_state() {
  err "Resetting Ginto runtime state..."

  stop_previous_instance
  stop_frpc_instances

  if command -v pkill >/dev/null 2>&1; then
    pkill -f "$MOBILE_ROUTER" >/dev/null 2>&1 || true
    pkill -f "configs/mobile.Caddyfile" >/dev/null 2>&1 || true
  fi

  rm -f "$PID_FILE" >/dev/null 2>&1 || true
  rm -f "$ROOT_DIR/configs/.webadmin_session_secret" >/dev/null 2>&1 || true
  rm -f "$ROOT_DIR/configs/webadmin.sqlite3" >/dev/null 2>&1 || true
  rm -f "$ROOT_DIR/configs/webadmin_mobile.sqlite3" >/dev/null 2>&1 || true
  rm -f "$ROOT_DIR/configs/instances_state.json" >/dev/null 2>&1 || true
  rm -f "$ROOT_DIR/configs/mobile.Caddyfile" >/dev/null 2>&1 || true

  rm -f "$AUTO_TLS_CERT" "$AUTO_TLS_KEY" >/dev/null 2>&1 || true
  rmdir "$TLS_DIR" >/dev/null 2>&1 || true

  find "$ROOT_DIR/configs" -maxdepth 1 -type f -name '*.toml' -delete >/dev/null 2>&1 || true
  find "$ROOT_DIR/configs" -maxdepth 1 -type f -name '.gntl-frpc-*.pid' -delete >/dev/null 2>&1 || true

  rm -rf "$MOBILE_LOG_DIR" >/dev/null 2>&1 || true
  mkdir -p "$MOBILE_LOG_DIR"

  err "Reset complete."
  err "State removed: auth DBs, sessions, instances, FRPC configs/pids, runtime logs, auto TLS certs."
}

if [ "$RUN_RESET" = "1" ]; then
  reset_runtime_state
  exit 0
fi

if [ "$RUN_UNINSTALL_SERVICE" = "1" ]; then
  uninstall_manager_service
  exit 0
fi

if [ "$RUN_INSTALL_SERVICE" = "1" ]; then
  install_manager_service
  exit $?
fi

if [ "$RUN_FRONTEND_INSTALL" = "1" ]; then
  frontend_install
  exit 0
fi

if [ "$RUN_FRONTEND_BUILD" = "1" ]; then
  frontend_build
  exit 0
fi

if [ "$RUN_FRONTEND_START" = "1" ]; then
  frontend_start
  exit 0
fi

if ! is_mobile_runtime; then
  prepare_frontend_for_backend_serving
fi

# Find a python executable (prefer python3)
find_python() {
  if command -v python3 >/dev/null 2>&1; then
    command -v python3
  elif command -v python >/dev/null 2>&1; then
    command -v python
  else
    echo ""
  fi
}

# Debian/Ubuntu split ensurepip out of the stdlib, so "python3 -m venv" fails
# until pythonX.Y-venv is installed. Name both the versioned and generic package.
python_venv_package_names() {
  local py ver
  py="${PYTHON:-python3}"
  ver="$("$py" -c 'import sys; print("%d.%d" % sys.version_info[:2])' 2>/dev/null || true)"
  if [ -n "$ver" ]; then
    printf 'python%s-venv\n' "$ver"
  fi
  printf 'python3-venv\n'
}

ensure_python_venv() {
  if [ -x "$VENV_DIR/bin/python" ] || [ -x "$VENV_DIR/bin/python3" ]; then
    return 0
  fi

  # A failed "python3 -m venv" leaves a partial directory behind; keeping it
  # would make the next run skip creation and silently use the system python.
  if [ -d "$VENV_DIR" ]; then
    err "[python] Removing incomplete virtualenv at $VENV_DIR"
    rm -rf "$VENV_DIR"
  fi

  err "[python] Creating virtualenv at $VENV_DIR"
  if "$PYTHON" -m venv "$VENV_DIR"; then
    return 0
  fi
  rm -rf "$VENV_DIR" >/dev/null 2>&1 || true

  if command -v apt-get >/dev/null 2>&1; then
    local pkg
    for pkg in $(python_venv_package_names); do
      err "[python] venv/ensurepip unavailable; installing $pkg ..."
      if maybe_sudo apt-get install -y "$pkg"; then
        break
      fi
    done
    if "$PYTHON" -m venv "$VENV_DIR"; then
      return 0
    fi
    rm -rf "$VENV_DIR" >/dev/null 2>&1 || true
  fi

  # No root, or the package is unavailable: the venv module itself still works,
  # only the bundled pip is missing. pip is bootstrapped further below.
  err "[python] Falling back to a pip-less virtualenv (pip is bootstrapped separately)..."
  if "$PYTHON" -m venv --without-pip "$VENV_DIR"; then
    return 0
  fi
  rm -rf "$VENV_DIR" >/dev/null 2>&1 || true

  if command -v virtualenv >/dev/null 2>&1; then
    err "[python] Trying the standalone virtualenv tool..."
    if virtualenv -p "$PYTHON" "$VENV_DIR"; then
      return 0
    fi
    rm -rf "$VENV_DIR" >/dev/null 2>&1 || true
  fi

  return 1
}

PYTHON=$(find_python)
OS_NAME=$(uname -s || true)

if is_mobile_runtime; then
  err "Detected mobile shell environment (Termux/iSH). Using mobile PHP+SQLite runtime."
  err "[frontend] Mobile runtime bootstrap: running frontend install + compile + build routines..."
  prepare_frontend_for_backend_serving
  run_mobile_server
  exit 0
fi

if [ -z "$PYTHON" ]; then
  err "Python not found. Attempting to install (best-effort)."
  case "$OS_NAME" in
    Linux*)
      if is_termux; then
        err "Detected Termux on Android. Installing python with pkg..."
        pkg update -y && pkg install -y python openssl || true
      elif command -v apt-get >/dev/null 2>&1; then
        err "Using apt-get to install python3... (may require sudo)"
        sudo apt-get update && sudo apt-get install -y python3 python3-venv python3-pip || true
      elif command -v dnf >/dev/null 2>&1; then
        err "Using dnf to install python3... (may require sudo)"
        sudo dnf install -y python3 python3-venv python3-pip || true
      elif command -v yum >/dev/null 2>&1; then
        err "Using yum to install python3... (may require sudo)"
        sudo yum install -y python3 python3-venv python3-pip || true
      elif command -v pacman >/dev/null 2>&1; then
        err "Using pacman to install python3... (may require sudo)"
        sudo pacman -Syu --noconfirm python python-virtualenv || true
      elif command -v apk >/dev/null 2>&1; then
        if is_ish_ios; then
          err "Detected iSH (iOS Alpine). Installing python3 with apk..."
        else
          err "Using apk to install python3..."
        fi
        apk update && apk add python3 py3-pip py3-virtualenv openssl || true
      else
        err "No supported package manager found."
        err "Android users: install via Termux and run: pkg install python"
        err "iOS users: run in iSH (apk add python3) or in a Homebrew-enabled shell on macOS."
      fi
      ;;
    Darwin*)
      if command -v brew >/dev/null 2>&1; then
        err "Using Homebrew to install python..."
        brew install python || true
      else
        err "Homebrew not found."
        err "If this is iOS shell without Homebrew, install Python in iSH (apk add python3) or use a Python-capable shell app."
        err "On macOS, install Homebrew then run this script again."
      fi
      ;;
    MINGW*|MSYS*|CYGWIN*|Windows_NT)
      err "Detected Windows environment. Please install Python 3 from https://www.python.org/downloads/windows/ and ensure 'python' is on PATH."
      ;;
    *)
      err "Unsupported OS: $OS_NAME. Please install Python 3 manually."
      ;;
  esac
  PYTHON=$(find_python)
fi

if [ -z "$PYTHON" ]; then
  err "Python still not found. Aborting."
  exit 1
fi

err "Using python: $PYTHON"

# Create venv if missing
if ! ensure_python_venv; then
  err "Could not create a Python virtualenv at $VENV_DIR"
  if is_debian_like; then
    err "Install the venv package and re-run: sudo apt-get install -y $(python_venv_package_names | head -n1)"
  fi
  exit 1
fi

VENV_PY="$VENV_DIR/bin/python"
VENV_PIP="$VENV_DIR/bin/pip"

if [ ! -x "$VENV_PY" ] && [ -x "$VENV_DIR/bin/python3" ]; then
  VENV_PY="$VENV_DIR/bin/python3"
fi

if [ -x "$VENV_PY" ]; then
  err "Using virtualenv python: $VENV_PY"
else
  err "Virtualenv python not found, falling back to system python: $PYTHON"
  VENV_PY="$PYTHON"
fi

# Ensure pip is available inside the venv. Some systems create venv without pip.
if [ -x "$VENV_PY" ]; then
  if ! "$VENV_PY" -m pip --version >/dev/null 2>&1; then
    err "pip not found in venv; attempting to bootstrap pip with ensurepip"
    if "$VENV_PY" -m ensurepip --upgrade >/dev/null 2>&1; then
      err "pip bootstrapped with ensurepip"
    else
      err "ensurepip failed; downloading get-pip.py as fallback"
      if command -v curl >/dev/null 2>&1; then
        curl -sS https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py || true
      elif command -v wget >/dev/null 2>&1; then
        wget -q -O /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py || true
      fi
      if [ -f /tmp/get-pip.py ]; then
        "$VENV_PY" /tmp/get-pip.py || true
        rm -f /tmp/get-pip.py || true
      else
        err "Could not obtain get-pip.py; pip may be unavailable."
      fi
    fi
  fi
fi

if [ -x "$VENV_PIP" ]; then
  "$VENV_PIP" install --upgrade pip
  "$VENV_PIP" install -r "$ROOT_DIR/requirements.txt"
else
  # fallback: use python -m pip
  "$VENV_PY" -m pip install --upgrade pip
  "$VENV_PY" -m pip install -r "$ROOT_DIR/requirements.txt"
fi

ensure_auto_tls
stop_previous_instance
prepare_desktop_tunnels || true
export GNTL_BIND_HOST="$BIND_HOST"

LAN_IP="$(detect_lan_ip)"

if [ -n "${GNTL_TLS_CERT:-}" ]; then
  LOCAL_APP_URL="https://127.0.0.1:2026"
  err "Starting server on https://${BIND_HOST}:2026"
  err "Local URL: $LOCAL_APP_URL"
  if [ -n "$LAN_IP" ] && { [ "$BIND_HOST" = "0.0.0.0" ] || [ "$BIND_HOST" = "::" ]; }; then
    err "Mobile URL (same Wi‑Fi): https://${LAN_IP}:2026  (https, self-signed - accept the warning)"
    err "Plain-HTTP mirror (no cert warning): http://${LAN_IP}:2027"
    lan_firewall_hint 2026 2027
  fi
else
  LOCAL_APP_URL="http://127.0.0.1:2026"
  err "Starting server on http://${BIND_HOST}:2026"
  err "Local URL: $LOCAL_APP_URL"
  if [ -n "$LAN_IP" ] && { [ "$BIND_HOST" = "0.0.0.0" ] || [ "$BIND_HOST" = "::" ]; }; then
    err "Mobile URL (same Wi‑Fi): http://${LAN_IP}:2026"
    lan_firewall_hint 2026
  fi
fi

PYTHONPATH="$BACKEND_SRC_DIR${PYTHONPATH:+:$PYTHONPATH}" "$VENV_PY" -m gntl.main &
SERVER_PID=$!
echo "$SERVER_PID" > "$PID_FILE"
if kill -0 "$SERVER_PID" >/dev/null 2>&1; then
  open_local_app_url "$LOCAL_APP_URL"
fi

cleanup() {
  rm -f "$PID_FILE" || true
}

trap cleanup EXIT INT TERM
wait "$SERVER_PID"